version: '3.8'

services:
  redis:
    image: redis
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      API_TOKEN: '${API_TOKEN}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      SERVER_PORT: '${SERVER_PORT}'
    volumes:
      - ./:/usr/src/app
